In [1]:
%pip install pandas numpy matplotlib scikit-learn

Requirement already satisfied: pandas in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.2)
Requirement already satisfied: matplotlib in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.1)
Requirement already satisfied: scikit-learn in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\spino\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\spino\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\spino\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\spino\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from pathlib import Path

In [3]:
print("hello")

hello

In [4]:
raw_df = pd.read_csv('../Dataset/final_sdb_dataset_clean.csv')
print(f"Raw dataset shape: {raw_df.shape}")
raw_df.head()

Raw dataset shape: (11676, 6)

    latitude  longitude  blue_band  green_band  depth  stumpf_ratio
0  15.043750  80.877083     0.0462      0.0360   2321      1.069613
1   9.627083  82.210417     0.0469      0.0344   3709      1.087608
2   8.377083  76.043750     0.0501      0.0337   1094      1.112729
3   8.085417  72.127083     0.0489      0.0336   2566      1.106772
4   9.085417  74.293750     0.0339      0.0244   2732      1.102934

In [5]:
# Filter optical solar penetration zone (depth <= 30m)
sdb_df = raw_df[raw_df['depth'] <= 30.0].copy().reset_index(drop=True)
print(f"Filtered SDB dataset shape: {sdb_df.shape}")
sdb_df.describe()

Filtered SDB dataset shape: (4548, 6)

,latitude,longitude,blue_band,green_band,depth,stumpf_ratio
count,4548.000000,4548.000000,4548.000000,4548.000000,4548.000000,482.000000
mean,25.568156,54.371902,0.070171,0.071358,13.690633,0.991108
std,3.895030,8.561133,0.035483,0.047502,8.871907,0.044342
min,6.043750,48.002083,0.008600,0.009400,1.000000,0.832094
25%,24.731250,50.147917,0.047577,0.041388,6.000000,0.957717
50%,25.731250,51.835417,0.059400,0.054913,13.000000,0.976481
75%,27.798958,53.939583,0.079162,0.082300,21.000000,1.023638
max,30.439583,89.960417,0.419400,0.467600,30.000000,1.174311

In [6]:
# Compute Stumpf log-ratio feature
sdb_df['stumpf_ratio'] = np.log(1000 * sdb_df['blue_band']) / np.log(1000 * sdb_df['green_band'])
sdb_df[['blue_band', 'green_band', 'stumpf_ratio', 'depth']].head()

   blue_band  green_band  stumpf_ratio  depth
0    0.09935     0.11890      0.962406     28
1    0.07100     0.08660      0.955479     14
2    0.05680     0.05180      1.023344     26
3    0.04905     0.04335      1.032774     23
4    0.08695     0.09920      0.971329      4

In [7]:
ra_df = pd.read_csv('../Dataset/final_sdb_dataset_clean.csv')

ra_df['stumpf_ratio'] = np.log(1000 * ra_df['blue_band']) / np.log(1000 * ra_df['green_band'])
print(f"Raw dataset shape: {ra_df.shape}")
 

ra_df.to_csv("../Dataset/final_sdb_dataset_clean.csv", index=False)

Raw dataset shape: (11676, 6)

In [ ]:
ra_df.head()

    latitude  longitude  blue_band  green_band  depth  stumpf_ratio
0  15.043750  80.877083     0.0462      0.0360   2321      1.069613
1   9.627083  82.210417     0.0469      0.0344   3709      1.087608
2   8.377083  76.043750     0.0501      0.0337   1094      1.112729
3   8.085417  72.127083     0.0489      0.0336   2566      1.106772
4   9.085417  74.293750     0.0339      0.0244   2732      1.102934